### PR TITLE
[GFM-9] - Removed custom template code for displaying toggle content …

### PR DESCRIPTION
**Pull request by joefitter**
…below radio, now uses new utility to render custom content as part of an optionGroup (used within radio-group)

https://jira.digital.homeoffice.gov.uk/browse/GFM-9

* Replaced custom HTML in how.html template with standard {{#radio-group}}
* Added childTemplate option to how-radio options to render a childElement within the radio item html
* Added new partial in common/partials used to wrap toggled content in a div.panel-indent and have id {toggle-id}-panel which is now used internally to automatically detect which element to toggle
* removed superfluous next arg in errors/index
* use hof#5e48ca0 which references fixes in passports modules

### CODE REVIEW

**Comment by JoeChapman** [comment]
@joefitter where are we with this?

**Comment by joefitter** [comment]
same place as we have been since the pr was submitted... Just waiting on a hof bump now though

**Comment by joefitter** [comment]
@JoeChapman @gxxm @bendiggle passing now :) can I get a 👍 ?

**Comment by gxxm** [comment]
:thumbsup:

**Pull request merged**
