### PR TITLE
GFM-147 - use HOF-template-partials

### PR DESCRIPTION
**Pull request by joefitter**
* removed apps/common
* moved email service to apps/gro
* moved email images to assets
* added hof-template-partials, bumped express-template-partials and hof-transpiler
* amended hof-transpiler to build translations from template-partials
* pass view from template partials to app.views

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @easternbloc @gxxm pls!

**Comment by JoeChapman** [comment]
@joefitter broken!

**Comment by joefitter** [comment]
@JoeChapman passing

**Comment by joefitter** [comment]
also @easternbloc @gxxm when you get a sec!

**Comment by gxxm** [comment]
:thumbsup: :thumbsup:

**Comment by JoeChapman** [comment]
rebase

**Comment by joefitter** [comment]
@JoeChapman @easternbloc mergy mergy plz

**Comment by JoeChapman** [comment]
LGTM

**Pull request merged**
