### PR TITLE
GFM-81 - updated /details step to use conditional labels

### PR DESCRIPTION
**Pull request by joefitter**
* if complaint is selected in first step, thie is reflected in the labels of details step

### CODE REVIEW

**Comment by joefitter** [comment]
another one - @JoeChapman @gxxm @bendiggle

**Comment by joefitter** [comment]
@JoeChapman @gxxm @bendiggle mind having a look?

**Comment by joefitter** [comment]
@bendiggle @gxxm @JoeChapman howzat?

**Comment by JoeChapman** [comment]
LGTM

**Comment by gxxm** [comment]
:thumbsup: :thumbsup:

**Pull request merged**
