### PR TITLE
GFM-46 - use hof-logger

### PR DESCRIPTION
**Pull request by joefitter**
- installed hof-logger
- removed bespoke logger
- add middleware to attach logger to req
- use req.logger in postcode controller for reporting api errors

### CODE REVIEW

**Comment by JoeChapman** [comment]
@joefitter are we still waiting for hof-logger to be published?

**Comment by joefitter** [comment]
yes

**Comment by joefitter** [comment]
fancy merging it?

**Comment by joefitter** [comment]
https://github.com/UKHomeOffice/hof-logger/pull/1

**Comment by JoeChapman** [comment]
@joefitter this isn't needed anymore is it?

**Comment by JoeChapman** [comment]
superceeded by hof-bootstrap

**Pull request closed without merging**
