### PR TITLE
GFM-45: Make error handler a HOF middleware and use it

### PR DESCRIPTION
**Pull request by JoeChapman**
- install latest HOF
- remove lib/errors
- use hof middelware error handler

### CODE REVIEW

**Comment by joefitter** [comment]
nice! Will merge when tests pass

**Comment by joefitter** [comment]
Hey @JoeChapman - there are a few issues with the acceptance tests here - all of which I have fixed and am waiting on things being merged. This will pass following a rebase once my bits are in

**Comment by JoeChapman** [comment]
@joefitter [Fix acceptance tests jira issue](https://jira.digital.homeoffice.gov.uk/browse/GFM-51) addresses the same problems. Am very glad to hear you have fixed them, awesome. 
Which PR is the fix in?

**Comment by joefitter** [comment]
There are a few issues fixed by a few different PRs - firstly forking not invalidating steps is part of the issue - my commit is here https://github.com/UKHomeOffice/passports-form-wizard/tree/bugfix/%2353-invalidate-unreachable-steps but needs forking merging in passports before can PR. 

https://github.com/UKHomeOffice/gro/pull/22/files fixes the rest of the tests - but this will need updating once the forks are in, and also the templateMixins PR - https://github.com/UKHomeOffice/passports-template-mixins/pull/57

**Comment by JoeChapman** [comment]
I can only suggest that you refactor the pr with the test fixes. Make the test fixes a separate PR.

**Comment by joefitter** [comment]
Sure I will do, but they wont pass until forking, and the following PR is merged

**Comment by JoeChapman** [comment]
@joefitter where are we with this?

**Comment by JoeChapman** [comment]
@joefitter this is passing now!

**Pull request merged**
