### PR TITLE
bugfix - fix travis not stopping on error

### PR DESCRIPTION
**Pull request by joefitter**
* moved `npm start` to scripts
* run as one command split with `&&`'s

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @gxxm @bendiggle passing now

**Comment by joefitter** [comment]
@JoeChapman @bendiggle @gxxm  - this speeds up failed build feedback

**Comment by JoeChapman** [comment]
this is working now, innit?

**Comment by joefitter** [comment]
no, this needs merging to speed up build fail feedback

**Pull request merged**
