### PR TITLE
GFM-151 - refine error message

### PR DESCRIPTION
**Pull request by joefitter**
* refined previous error message
* added existing error message for other enquiries
* added acceptance tests

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @gxxm @easternbloc

**Comment by easternbloc** [comment]
Where is this copy coming from? Has a content designer worked on this?

**Comment by joefitter** [comment]
https://jira.digital.homeoffice.gov.uk/browse/GFM-151 - David Harding confirmed the content for this particular error message - other content changes were missed before

**Comment by easternbloc** [comment]
Cool will merge when the tests pass...

**Comment by easternbloc** [comment]
👎

**Comment by joefitter** [comment]
this failed randomly because of Travis it looks like. meh

**Pull request merged**
