### PR TITLE
GFM-80 - updated additional step to include extra field - additional-…

### PR DESCRIPTION
**Pull request by joefitter**
…name if about-radio is wrong-certificate

### CODE REVIEW

**Comment by joefitter** [comment]
@JoeChapman @gxxm @bendiggle passing now

**Comment by joefitter** [comment]
@JoeChapman @gxxm @bendiggle happy with this?

**Comment by JoeChapman** [comment]
a failing tests

**Comment by joefitter** [comment]
no - that was the push - the PR build is passing

**Comment by JoeChapman** [comment]
does this have an acceptance test?

**Comment by joefitter** [comment]
no but I _guess_ I could write one... ;)

**Comment by JoeChapman** [comment]
_you_ don't have to write one, but someone does and preferably before this code is merged

**Comment by joefitter** [comment]
It's ok, I'll do it

**Comment by joefitter** [comment]
@JoeChapman done-did

**Comment by JoeChapman** [comment]
LGTM

**Comment by joefitter** [comment]
@bendiggle @gxxm can I get another 👍 please?

**Comment by bendiggle** [comment]
LGTM!

**Comment by joefitter** [comment]
cheers!

**Pull request merged**
