### PR TITLE
Resolve GFM-118: Fix Docker build

### PR DESCRIPTION
**Pull request by JoeChapman**
- remove NODE_ENV='development' setting from Dockerfile
- remove the condition for NODE_ENV='development' from run.sh
- always use `npm start` to run the app in a container

### CODE REVIEW

**Comment by bendiggle** [comment]
LGTM

**Comment by JoeChapman** [comment]
@allandegnan I would also like your feedback to this. It's small, but I would like to know it makes sense from someone with more Docker experience than I.

**Comment by joefitter** [comment]
LGTM but as @JoeChapman said, would be good to get the opinion of someone who knows about these kind of things 😄

**Comment by allandegnan** [comment]
LGTM

**Pull request merged**
