### PR TITLE
Bundler seems to be causing issues with travis installing phantom

### PR DESCRIPTION
**Pull request by easternbloc**
so lets use 2.0 which is already installed on travis

### CODE REVIEW

**Comment by easternbloc** [comment]
@JoeChapman

**Comment by easternbloc** [comment]
@JoeChapman

**Comment by easternbloc** [comment]
@JoeChapman

**Comment by easternbloc** [comment]
@JoeChapman

**Comment by easternbloc** [comment]
@JoeChapman

**Comment by joefitter** [comment]
@JoeChapman could you look at this PR please

**Comment by JoeChapman** [comment]
If this passes, I might merge it later

**Comment by easternbloc** [comment]
@JoeChapman

**Pull request merged**
